DbFilePath = "/var/lib/gemrutracker/db.sqlite"
HttpProxyAddress = ""
ListenAddress = ":1965"
UpdatePeriodHours = 24
LogLevel = "info"
UpdateRecordCount = 1000
ParserThreadCount = 8
CertFilePath = "/var/lib/gemrutracker/cert.pem"
KeyFilePath = "/var/lib/gemrutracker/key.pem"
