WorkDir = "/var/lib/gemrutracker/"
HttpProxyAddress = ""
ListenAddress = ":1965"
UpdatePeriodHours = 24
LogLevel = "info"
UpdateForwardRecordCount = 1000
UpdateBackwardRecordCount = 0
ParserThreadCount = 8
CertFilePath = "/var/lib/gemrutracker/cert.pem"
KeyFilePath = "/var/lib/gemrutracker/key.pem"
