CREATE TABLE "data" ("id" INTEGER NOT NULL UNIQUE, "magnet" TEXT NOT NULL, "forum_id" INTEGER NOT NULL, PRIMARY KEY("id")) WITHOUT ROWID;
CREATE TABLE "forums" ("id" INTEGER NOT NULL UNIQUE, "name" TEXT NOT NULL UNIQUE, PRIMARY KEY("id")) WITHOUT ROWID;
CREATE VIRTUAL TABLE "titles" USING fts5 (title, columnsize=0, detail=none);

INSERT INTO "forums" ("id", "name") VALUES ('1', 'Apple');
INSERT INTO "forums" ("id", "name") VALUES ('2', 'Hi-Res форматы, оцифровки');
INSERT INTO "forums" ("id", "name") VALUES ('3', 'Авто и мото');
INSERT INTO "forums" ("id", "name") VALUES ('4', 'Аудиокниги');
INSERT INTO "forums" ("id", "name") VALUES ('5', 'Джазовая и Блюзовая музыка');
INSERT INTO "forums" ("id", "name") VALUES ('6', 'Документалистика и юмор');
INSERT INTO "forums" ("id", "name") VALUES ('7', 'Игры');
INSERT INTO "forums" ("id", "name") VALUES ('8', 'Кино, Видео и ТВ');
INSERT INTO "forums" ("id", "name") VALUES ('9', 'Книги и журналы');
INSERT INTO "forums" ("id", "name") VALUES ('10', 'Мобильные устройства');
INSERT INTO "forums" ("id", "name") VALUES ('11', 'Музыка');
INSERT INTO "forums" ("id", "name") VALUES ('12', 'Музыкальное видео');
INSERT INTO "forums" ("id", "name") VALUES ('13', 'Новости');
INSERT INTO "forums" ("id", "name") VALUES ('14', 'Обсуждения, встречи, общение');
INSERT INTO "forums" ("id", "name") VALUES ('15', 'Обучающее видео');
INSERT INTO "forums" ("id", "name") VALUES ('16', 'Обучение иностранным языкам');
INSERT INTO "forums" ("id", "name") VALUES ('17', 'Популярная музыка');
INSERT INTO "forums" ("id", "name") VALUES ('18', 'Программы и Дизайн');
INSERT INTO "forums" ("id", "name") VALUES ('19', 'Разное');
INSERT INTO "forums" ("id", "name") VALUES ('20', 'Рок-музыка');
INSERT INTO "forums" ("id", "name") VALUES ('21', 'Сериалы');
INSERT INTO "forums" ("id", "name") VALUES ('22', 'Спорт');
INSERT INTO "forums" ("id", "name") VALUES ('23', 'Электронная музыка');
